### ISSUE TITLE
StephanP: Mein neues Issue (edited)

### ISSUE THREAD

**Issue by HypoStephan** [hypoport/git_101_training#8]
### Test the best

> Zitat

1. @twessendorf 

Edit

**Comment by HypoStephan** [comment]
Ein erster Kommentar

**Comment by HypoStephan** [comment]
#4 Sehe ich auch so :)

**Comment by HypoStephan** [comment]
> ### Test the best
> > Zitat
> 
> 1. @twessendorf
> 
> Edit

Antwort

**Comment by twessendorf** [comment]
Duplicate of #1

**Comment by twessendorf** [comment]
Duplicate of #2

**Comment by twessendorf** [comment]
Duplicate of #8

**Comment by twessendorf** [comment]
Duplicate of #8

**Comment by twessendorf** [comment]
Duplicate of #6

**Comment by HypoStephan** [comment]
Duplicate of #2
